### ISSUE TITLE
Events/hooks system of some sort

### ISSUE THREAD

**Issue by ahwitz** [ahwitz/Vida6#1]
@crantila - opinions? there's a bunch of events I can hook on to, and I'm thinking about including the [default MEI one](https://github.com/ddmal/mei.js) but I don't know if this'll work with your plans

**Comment by crantila** [comment]
I took a look at `mei.js`. There didn't seem to be anything specific to MEI but the name, right? It looks neither helpful nor unhelpful for my own interests.

As you know, in Christopherland we're using [NuclearJS](https://optimizely.github.io/nuclear-js/). Nothing about it is React-specific, and I've come to appreciate that the application structure they encourage really does improve modularity and make it easier to test. It's pub/sub at the core, and it would certainly be possible to add all sorts of "actions" that only change the application state depends on who's listening. Especially as Vida grows a complex of events and interactions that require data manipulation, Nuclear could turn out to be a huge asset. Maybe it's a little weird to use a state-and-events library primarily for events; all I'm saying is that it's worth considering.

There's also the [Microcosm](https://github.com/vigetlabs/microcosm) library, which the Nuclear authors recommend for smaller applications. It seems like they made it "lighter" by not having a rigourous event system though, which is sort of the point here.

So that's my opinions. I have experience with one thing and I recommend it, but `mei.js` also seems like a reasonable choice. In terms of working with Christopherland, it's probably more a question of what the events are than how they're produced and consumed.

**Comment by ahwitz** [comment]
The problem with Nuclear/Microcosm is that I want whatever system I end up using to be self-contained and lightweight, as well as not-necessarily-React-related; the plan was to build an interface in the Verovio Nuclear model to interact with whatever I build, rather than as what I build

**Comment by crantila** [comment]
At [72&nbsp;KB for the 1.3.0 release](https://github.com/optimizely/nuclear-js/blob/master/dist/nuclear.min.js) I concede Nuclear is not the smallest choice (if that's what "lightweight" meant). But the core, as mentioned, uses `dispatch()` and `observe()` as a straight-forward pub/sub system. So if that's all someone wants to do, the API is indeed lightweight. Although the "actions" and "getters" functions make complex data manipulation easier, they are provided by you, so Nuclear is as self-contained as `mei.js`. In terms of React bindings, that's an extra "plus" for people using it, but it's certainly not required. No matter which event system you choose, you'll have to write bindings to Verovio yourself.

That doesn't mean NuclearJS is the right choice&mdash;but if it's a bad choice, I don't believe it's for the reasons above. I would be more concerned about Nuclear being overkill (insert joke about solar power). The complexity comes from the state management features, especially the "actions" and "getters" functions, which on the other hand provide a rigourous structure and open up a lot of possibilities for Vida. You could read [this blog post](http://tilomitra.com/front-end-apps-with-nuclearjs/) about using NuclearJS or [this one](https://gist.github.com/mcmire/693df5705e192413cec8) comparing three flux-pattern libraries (one of which doesn't have a pub/sub dispatcher). Again, even though it was created by the React developers, and even though it's used most commonly with React, the flux pattern (and NuclearJS) can be used anywhere.

But if you're not planning on adding data manipulation to Vida itself, NuclearJS is indeed a bad choice. My understanding is that complicated MEI document manipulation is on the table, and Nuclear would provide a structure for both events and data flow. Did you have a structure in mind for data management already? That might help resolve this.

**Comment by ahwitz** [comment]
taken care of the easy way, by ignoring your opinions
